from django.urls import path

from .views import (
    AdminDashboardView,
    AdminAnnouncementView,
    AdminAnalyticsView,
    AdminParticipantActionView,
    AdminParticipantBulkActionView,
    AdminParticipantsView,
    AdminSystemSettingsView,
    AdminRolesView,
    AdminUserActionView,
    AdminUserBulkActionView,
    AdminUserDetailView,
    AdminUsersView,
    EventDetailView,
    EventFullDetailView,
    EventActionView,
    EventBulkActionView,
    EventListCreateView,
    LoginView,
    ChangePasswordView,
    GlobalSearchView,
    LogoutView,
    NotificationActionView,
    NotificationDetailView,
    NotificationListView,
    ProfileView,
    RefreshView,
    RegisterView,
    RegistrationDetailView,
    RegistrationListCreateView,
    RegistrationInviteActionView,
    RegistrationJoinRequestView,
    RegistrationJoinAcceptView,
    UserEnrollmentListView,
    ImageUploadView,
    AdminAnalyticsExportView,
    AdminParticipantExportView,
)


urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/refresh", RefreshView.as_view()),
    path("users/profile", ProfileView.as_view()),
    path("users/enrollments", UserEnrollmentListView.as_view()),
    path("users/password", ChangePasswordView.as_view()),
    path("notifications", NotificationListView.as_view()),
    path("notifications/actions/<str:action>", NotificationActionView.as_view()),
    path("notifications/<str:notification_id>/<str:action>", NotificationDetailView.as_view()),
    path("notifications/<str:notification_id>", NotificationDetailView.as_view()),
    path("search", GlobalSearchView.as_view()),
    path("events", EventListCreateView.as_view()),
    path("events/bulk/<str:action>", EventBulkActionView.as_view()),
    path("events/<str:event_id>/details", EventFullDetailView.as_view()),
    path("events/<str:event_id>", EventDetailView.as_view()),
    path("events/<str:event_id>/<str:action>", EventActionView.as_view()),
    path("registrations", RegistrationListCreateView.as_view()),
    path("registrations/<str:registration_id>", RegistrationDetailView.as_view()),
    path("registrations/<str:registration_id>/respond-invite", RegistrationInviteActionView.as_view()),
    path("registrations/<str:registration_id>/request-join", RegistrationJoinRequestView.as_view()),
    path("registrations/<str:registration_id>/accept-join", RegistrationJoinAcceptView.as_view()),
    path("admin/dashboard", AdminDashboardView.as_view()),
    path("admin/analytics", AdminAnalyticsView.as_view()),
    path("admin/users", AdminUsersView.as_view()),
    path("admin/system", AdminSystemSettingsView.as_view()),
    path("admin/roles", AdminRolesView.as_view()),
    path("admin/users/bulk/<str:action>", AdminUserBulkActionView.as_view()),
    path("admin/users/<str:user_id>", AdminUserDetailView.as_view()),
    path("admin/users/<str:user_id>/<str:action>", AdminUserActionView.as_view()),
    path("admin/events", EventListCreateView.as_view()),
    path("admin/participants", AdminParticipantsView.as_view()),
    path("admin/participants/bulk/<str:action>", AdminParticipantBulkActionView.as_view()),
    path("admin/participants/<str:registration_id>/<str:action>", AdminParticipantActionView.as_view()),
    path("upload/image", ImageUploadView.as_view()),
    path("admin/analytics/export/<str:format>", AdminAnalyticsExportView.as_view()),
    path("admin/participants/export/<str:format>", AdminParticipantExportView.as_view()),
    path("admin/announcements", AdminAnnouncementView.as_view()),
]
