from django.contrib.auth.hashers import make_password
from django.core.management.base import BaseCommand

from api.documents import Event, User


class Command(BaseCommand):
    help = "Seed MongoDB with demo users and events."

    def handle(self, *args, **options):
        admin = User.objects(email="admin@carpedium.dev").first()
        if not admin:
            admin = User(
                full_name="Carpedium Admin",
                email="admin@carpedium.dev",
                password_hash=make_password("Admin@12345"),
                role="admin",
            ).save()

        Event.objects(name__in=["Neon Hack Summit", "Solo Spotlight"]).delete()

        demo_events = [
            {
                "name": "Neon Hack Summit 2026",
                "description": "A 24-hour innovation arena with problem statements, mentor rounds, prototype demos, judging, certificates, and cash prizes for winning teams.",
                "banner_image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952",
                "date": "2026-08-12",
                "time": "10:00",
                "venue": "Innovation Dome",
                "registration_deadline": "2026-08-08",
                "event_type": "team",
                "team_size": 3,
                "category": "Technology",
                "maximum_seats": 80,
                "available_seats": 80,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "Solo Spotlight Night",
                "description": "A premium stage for solo singing, spoken word, stand-up, beatboxing, and individual performance with professional sound, lighting, and jury scoring.",
                "banner_image": "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
                "date": "2026-08-18",
                "time": "18:00",
                "venue": "Open Air Theatre",
                "registration_deadline": "2026-08-14",
                "event_type": "individual",
                "category": "Culture",
                "maximum_seats": 120,
                "available_seats": 120,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "Design Carnival",
                "description": "A creative showcase for poster design, UI challenges, brand identity, photography walls, portfolio reviews, and live design battles.",
                "banner_image": "https://images.unsplash.com/photo-1497366754035-f200968a6e72",
                "date": "2026-08-22",
                "time": "11:00",
                "venue": "Creative Studio Hall",
                "registration_deadline": "2026-08-19",
                "event_type": "individual",
                "category": "Design",
                "maximum_seats": 90,
                "available_seats": 90,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "Startup Pitch Arena",
                "description": "A founder-style pitch competition with idea validation, business model judging, investor-style Q&A, prototype review, and winning grants.",
                "banner_image": "https://images.unsplash.com/photo-1556761175-b413da4baf72",
                "date": "2026-08-24",
                "time": "14:00",
                "venue": "Incubation Center",
                "registration_deadline": "2026-08-20",
                "event_type": "team",
                "team_size": 3,
                "category": "Entrepreneurship",
                "maximum_seats": 60,
                "available_seats": 60,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "Code Relay",
                "description": "A timed programming relay where team members solve chained problems, pass logic forward, debug under pressure, and compete on leaderboard scoring.",
                "banner_image": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
                "date": "2026-08-26",
                "time": "13:00",
                "venue": "Computer Lab 3",
                "registration_deadline": "2026-08-22",
                "event_type": "team",
                "team_size": 4,
                "category": "Technology",
                "maximum_seats": 72,
                "available_seats": 72,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "AI Prompt Battle",
                "description": "An individual AI creativity contest with prompt engineering rounds, output evaluation, constraint challenges, and originality scoring.",
                "banner_image": "https://images.unsplash.com/photo-1677442136019-21780ecad995",
                "date": "2026-08-28",
                "time": "12:00",
                "venue": "AI Lab",
                "registration_deadline": "2026-08-24",
                "event_type": "individual",
                "category": "Artificial Intelligence",
                "maximum_seats": 70,
                "available_seats": 70,
                "status": "completed",
                "created_by": admin,
            },
            {
                "name": "Robotics Line Follower",
                "description": "A robotics challenge with track trials, sensor calibration, timed runs, penalty rules, technical inspection, and final race scoring.",
                "banner_image": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e",
                "date": "2026-08-30",
                "time": "10:30",
                "venue": "Robotics Workshop",
                "registration_deadline": "2026-08-26",
                "event_type": "team",
                "team_size": 3,
                "category": "Robotics",
                "maximum_seats": 50,
                "available_seats": 50,
                "status": "ongoing",
                "created_by": admin,
            },
            {
                "name": "Treasure Hunt X",
                "description": "A campus-wide team hunt with clue solving, QR checkpoints, time penalties, puzzle rounds, map navigation, and final leaderboard ranking.",
                "banner_image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
                "date": "2026-09-01",
                "time": "09:30",
                "venue": "Campus Central Lawn",
                "registration_deadline": "2026-08-28",
                "event_type": "team",
                "team_size": 5,
                "category": "Adventure",
                "maximum_seats": 100,
                "available_seats": 100,
                "status": "ongoing",
                "created_by": admin,
            },
            {
                "name": "Debate Royale",
                "description": "An individual debate competition with prepared motions, rebuttal rounds, judge scoring, time limits, and best-speaker awards.",
                "banner_image": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2",
                "date": "2026-09-03",
                "time": "15:00",
                "venue": "Auditorium 2",
                "registration_deadline": "2026-08-30",
                "event_type": "individual",
                "category": "Literary",
                "maximum_seats": 80,
                "available_seats": 80,
                "status": "ongoing",
                "created_by": admin,
            },
            {
                "name": "Quiz Conclave",
                "description": "A team quiz event with general knowledge, tech, pop culture, audio-visual rounds, rapid fire, buzzer rounds, and final scoring.",
                "banner_image": "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b",
                "date": "2026-09-05",
                "time": "11:30",
                "venue": "Seminar Hall A",
                "registration_deadline": "2026-09-01",
                "event_type": "team",
                "team_size": 3,
                "category": "Quiz",
                "maximum_seats": 90,
                "available_seats": 90,
                "status": "ongoing",
                "created_by": admin,
            },
            {
                "name": "Photography Walk",
                "description": "An individual photography event with theme briefing, campus photo walk, editing window, submission review, and jury-led visual storytelling awards.",
                "banner_image": "https://images.unsplash.com/photo-1452587925148-ce544e77e70d",
                "date": "2026-09-07",
                "time": "07:00",
                "venue": "Campus Gate",
                "registration_deadline": "2026-09-03",
                "event_type": "individual",
                "category": "Photography",
                "maximum_seats": 75,
                "available_seats": 75,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Film Making Sprint",
                "description": "A team film challenge with theme reveal, script development, shooting window, editing deadline, screening, and jury awards.",
                "banner_image": "https://images.unsplash.com/photo-1485846234645-a62644f84728",
                "date": "2026-09-09",
                "time": "09:00",
                "venue": "Media Lab",
                "registration_deadline": "2026-09-05",
                "event_type": "team",
                "team_size": 5,
                "category": "Film",
                "maximum_seats": 60,
                "available_seats": 60,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Dance Crew Showdown",
                "description": "A team dance competition with stage rehearsals, music checks, choreography scoring, costume review, lighting cues, and finale performances.",
                "banner_image": "https://images.unsplash.com/photo-1547153760-18fc86324498",
                "date": "2026-09-11",
                "time": "18:30",
                "venue": "Main Auditorium",
                "registration_deadline": "2026-09-07",
                "event_type": "team",
                "team_size": 8,
                "category": "Dance",
                "maximum_seats": 120,
                "available_seats": 120,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Battle of Bands",
                "description": "A team music event with live band performances, soundcheck slots, instrument setup, audience voting, jury scoring, and headline finale.",
                "banner_image": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
                "date": "2026-09-13",
                "time": "19:00",
                "venue": "Amphitheatre",
                "registration_deadline": "2026-09-09",
                "event_type": "team",
                "team_size": 6,
                "category": "Music",
                "maximum_seats": 70,
                "available_seats": 70,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Fashion Runway",
                "description": "A fashion showcase with theme-based walks, designer notes, grooming slots, backstage coordination, jury scoring, and best-look awards.",
                "banner_image": "https://images.unsplash.com/photo-1469334031218-e382a71b716b",
                "date": "2026-09-15",
                "time": "20:00",
                "venue": "Convention Stage",
                "registration_deadline": "2026-09-11",
                "event_type": "team",
                "team_size": 8,
                "category": "Fashion",
                "maximum_seats": 100,
                "available_seats": 100,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Drama Stagecraft",
                "description": "A theatre event with one-act plays, script checks, prop coordination, stage timing, acting evaluation, and best-production awards.",
                "banner_image": "https://images.unsplash.com/photo-1503095396549-807759245b35",
                "date": "2026-09-17",
                "time": "17:30",
                "venue": "Black Box Theatre",
                "registration_deadline": "2026-09-13",
                "event_type": "team",
                "team_size": 10,
                "category": "Theatre",
                "maximum_seats": 80,
                "available_seats": 80,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Eco Innovation Challenge",
                "description": "A sustainability challenge for prototypes, campaigns, and campus solutions with impact scoring, feasibility review, and presentation rounds.",
                "banner_image": "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9",
                "date": "2026-09-19",
                "time": "10:00",
                "venue": "Green Innovation Lab",
                "registration_deadline": "2026-09-15",
                "event_type": "team",
                "team_size": 4,
                "category": "Sustainability",
                "maximum_seats": 70,
                "available_seats": 70,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Business Case League",
                "description": "A team case-study league with business diagnostics, deck creation, financial reasoning, timed presentations, and executive-style judging.",
                "banner_image": "https://images.unsplash.com/photo-1552664730-d307ca884978",
                "date": "2026-09-21",
                "time": "13:30",
                "venue": "Management Block",
                "registration_deadline": "2026-09-17",
                "event_type": "team",
                "team_size": 4,
                "category": "Management",
                "maximum_seats": 84,
                "available_seats": 84,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Esports Valorant Cup",
                "description": "A team esports cup with match lobbies, bracket fixtures, anti-cheat checks, map veto, live scoring, and streamed finals.",
                "banner_image": "https://images.unsplash.com/photo-1542751371-adc38448a05e",
                "date": "2026-09-23",
                "time": "16:00",
                "venue": "Gaming Lab",
                "registration_deadline": "2026-09-19",
                "event_type": "team",
                "team_size": 5,
                "category": "Esports",
                "maximum_seats": 80,
                "available_seats": 80,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Cricket Premier League",
                "description": "A team cricket tournament with league fixtures, knockout rounds, toss supervision, umpire scoring, player-of-the-match awards, and finals ceremony.",
                "banner_image": "https://images.unsplash.com/photo-1531415074968-036ba1b575da",
                "date": "2026-09-02",
                "time": "08:00",
                "venue": "Main Cricket Ground",
                "registration_deadline": "2026-08-29",
                "event_type": "team",
                "team_size": 11,
                "category": "Sports - Cricket",
                "maximum_seats": 160,
                "available_seats": 160,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Football Championship",
                "description": "A full-field football championship with squad registration, group stage matches, referee-led scoring, rolling substitutions, and trophy presentation.",
                "banner_image": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d",
                "date": "2026-09-04",
                "time": "07:30",
                "venue": "University Football Arena",
                "registration_deadline": "2026-08-31",
                "event_type": "team",
                "team_size": 11,
                "category": "Sports - Football",
                "maximum_seats": 176,
                "available_seats": 176,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Basketball 5v5 Cup",
                "description": "A competitive basketball cup with 5v5 team entries, timed quarters, official scorekeeping, foul tracking, semifinals, and finals.",
                "banner_image": "https://images.unsplash.com/photo-1546519638-68e109498ffc",
                "date": "2026-09-06",
                "time": "16:00",
                "venue": "Indoor Sports Complex",
                "registration_deadline": "2026-09-02",
                "event_type": "team",
                "team_size": 5,
                "category": "Sports - Basketball",
                "maximum_seats": 120,
                "available_seats": 120,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Volleyball Clash",
                "description": "A team volleyball tournament with best-of-three sets, referee supervision, rotation rules, service tracking, and medals for finalists.",
                "banner_image": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1",
                "date": "2026-09-08",
                "time": "15:30",
                "venue": "Central Volleyball Court",
                "registration_deadline": "2026-09-04",
                "event_type": "team",
                "team_size": 6,
                "category": "Sports - Volleyball",
                "maximum_seats": 96,
                "available_seats": 96,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Badminton Singles Open",
                "description": "An individual badminton event with knockout draws, court allocation, match officials, scorecards, warm-up slots, and winner certificates.",
                "banner_image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea",
                "date": "2026-09-10",
                "time": "09:00",
                "venue": "Indoor Badminton Hall",
                "registration_deadline": "2026-09-06",
                "event_type": "individual",
                "category": "Sports - Badminton",
                "maximum_seats": 64,
                "available_seats": 64,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Tennis Singles Classic",
                "description": "An individual tennis classic with seeded brackets, chair umpire scoring, court schedules, tie-break rules, and championship finals.",
                "banner_image": "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6",
                "date": "2026-09-12",
                "time": "08:30",
                "venue": "Tennis Court 1",
                "registration_deadline": "2026-09-08",
                "event_type": "individual",
                "category": "Sports - Tennis",
                "maximum_seats": 48,
                "available_seats": 48,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Table Tennis Knockout",
                "description": "A fast-paced individual table tennis knockout with best-of-five games, umpire sheets, equipment checks, and live bracket updates.",
                "banner_image": "https://images.unsplash.com/photo-1534158914592-062992fbe900",
                "date": "2026-09-14",
                "time": "10:00",
                "venue": "Recreation Hall",
                "registration_deadline": "2026-09-10",
                "event_type": "individual",
                "category": "Sports - Table Tennis",
                "maximum_seats": 64,
                "available_seats": 64,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Athletics Track Meet",
                "description": "A multi-event athletics meet featuring 100m, 200m, relay, long jump, shot put, lane assignments, timing officials, and podium awards.",
                "banner_image": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5",
                "date": "2026-09-16",
                "time": "07:00",
                "venue": "College Athletics Track",
                "registration_deadline": "2026-09-12",
                "event_type": "individual",
                "category": "Sports - Athletics",
                "maximum_seats": 140,
                "available_seats": 140,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Chess Masters Arena",
                "description": "An individual chess tournament with Swiss pairings, digital clocks, arbiter supervision, tie-break scoring, and rated-style match discipline.",
                "banner_image": "https://images.unsplash.com/photo-1529699211952-734e80c4d42b",
                "date": "2026-09-18",
                "time": "11:00",
                "venue": "Seminar Hall B",
                "registration_deadline": "2026-09-14",
                "event_type": "individual",
                "category": "Sports - Chess",
                "maximum_seats": 80,
                "available_seats": 80,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Kabaddi League",
                "description": "A team kabaddi league with squad entries, raid timing, official referees, bonus-line rules, group rounds, playoffs, and final trophies.",
                "banner_image": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55",
                "date": "2026-09-20",
                "time": "17:00",
                "venue": "Outdoor Kabaddi Court",
                "registration_deadline": "2026-09-16",
                "event_type": "team",
                "team_size": 7,
                "category": "Sports - Kabaddi",
                "maximum_seats": 112,
                "available_seats": 112,
                "status": "upcoming",
                "created_by": admin,
            },
            {
                "name": "Swimming Sprint Challenge",
                "description": "An individual swimming challenge with 50m freestyle, 100m freestyle, heat timings, lifeguard supervision, lane allocation, and medal rounds.",
                "banner_image": "https://images.unsplash.com/photo-1530549387789-4c1017266635",
                "date": "2026-09-22",
                "time": "06:30",
                "venue": "Aquatic Center",
                "registration_deadline": "2026-09-18",
                "event_type": "individual",
                "category": "Sports - Swimming",
                "maximum_seats": 72,
                "available_seats": 72,
                "status": "upcoming",
                "created_by": admin,
            },
        ]

        fee_by_category = {
            "Sports": 250,
            "Technology": 500,
            "Artificial Intelligence": 450,
            "Entrepreneurship": 600,
            "Robotics": 550,
            "Esports": 400,
            "Management": 350,
            "Design": 300,
        }

        for payload in demo_events:
            payload["registration_fee"] = 0
            payload.setdefault("coordinator", "CarpeDiem Events Desk")
            payload.setdefault("rules", "Carry a valid college ID. Report 20 minutes before the scheduled time. Judges and coordinators decisions are final.")
            payload.setdefault("faq", "Bring your registration confirmation and required personal equipment. Schedule updates will be shared by the coordinator.")
            payload.setdefault("prize_details", "Winner, runner-up, and finalist recognition with certificates and event prizes.")
            payload.setdefault("is_archived", False)
            payload.setdefault("is_published", True)
            payload.setdefault(
                "maximum_teams",
                payload["maximum_seats"] // payload.get("team_size", 1) if payload["event_type"] == "team" else 0,
            )
            Event.objects(name=payload["name"]).modify(
                upsert=True,
                new=True,
                set__created_by=admin,
                **{f"set__{key}": value for key, value in payload.items() if key != "created_by"},
            )

        self.stdout.write(self.style.SUCCESS("Seeded MongoDB. Admin login: admin@carpedium.dev / Admin@12345"))
